//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event_Management_System_BootCamp.DbContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Hall
    {

      

        public int Id { get; set; }

        [Required(AllowEmptyStrings = true, ErrorMessage = "Please Enter Hall Name")]
        [Display(Name = "Hall Name")]
        public string HallName { get; set; }

        [Required(AllowEmptyStrings = true, ErrorMessage = "Please Enter Time Slot")]
        [Display(Name = "Time Slot")]
        public string TimeSlot { get; set; }

        [Required(AllowEmptyStrings = true, ErrorMessage = "Please Enter Seating Capacity")]
        [Display(Name = "Seating Capacity")]
        public Nullable<int> SeatingCapacity { get; set; }

        [Required(AllowEmptyStrings = true, ErrorMessage = "Please Enter Minimum Booking Capacity")]
        [Display(Name = "Minimum Capacity")]
        public Nullable<int> MinimumBookingCapacity { get; set; }


        [Required(AllowEmptyStrings = true, ErrorMessage = "Please Enter Hall Address")]
        [Display(Name = "Address")]
        public string Address { get; set; }


      
        public string User_ID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
