//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event_Management_System_BootCamp.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Services()
        {
            this.HallBooking = new HashSet<HallBooking>();
        }
    
        public int Id { get; set; }
        public int Dj_id { get; set; }
        public int Menu_id { get; set; }
        public int Decoration_id { get; set; }
    
        public virtual Decoration Decoration { get; set; }
        public virtual Dj Dj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HallBooking> HallBooking { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
